### ISSUE TITLE
Not align with "dim: feature dimension (default:128)", "K: queue size; number of negative keys (default: 65536)"

### ISSUE THREAD

**Issue by NickChang97** [KyleZheng1997/ReSSL#4]
https://github.com/KyleZheng1997/ReSSL/blob/3e6644d6790b2fa1b68bf527d2fa15fbc7ad9412/network/ressl.py#L12

**Comment by KyleZheng1997** [comment]
Thank you for pointing out the mistake, I have updated some comments to align my implementations
